### ISSUE TITLE
Excuse me, could you explain "You may need to polyfill Object.assign"

### ISSUE THREAD

**Issue by thearabbit** [Akryum/vue-meteor-tracker#10]
Excuse me, could you explain "You may need to polyfill Object.assign"

**Comment by Akryum** [comment]
If you target a [browser that doesn't support it](http://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign_a_href=_https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign_title=_MDN_documentation_img_src=_../mdn.png_alt=_MDN_(Mozilla_Development_Network)_logo_width=_15_height=_13_/_/a_nbsp;), you need to include a [polyfill](https://en.wikipedia.org/wiki/Polyfill) like [this one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) in your app.

**Comment by thearabbit** [comment]
Thanks for your reply.
