### ISSUE TITLE
Tracker nonsense, help plz

### ISSUE THREAD

**Issue by janat08** [Akryum/vue-meteor-tracker#14]
[Vue warn]: Error in created hook: "Error: You must provide either a function or an object with the update() method."

```
    data: {
      listings: {
        params() {
          return {stuff: this.name}
        },
        update ({param}) {
          if(param.length != 0){
          return AuctionItems.find({name: param.stuff, active: false, topBid: {$exists: true}}).fetch()
        } else {
          return ["none"]
        }
        return {sd: 1}
        }
      },
    }
```

**Comment by Akryum** [comment]
The [API has changed](https://github.com/Akryum/vue-meteor-tracker/commit/29c56187c7eb6a080491453860f45f44e66f7400), you no longer wrap in a `data` object. [Here is the doc](https://github.com/Akryum/vue-meteor-tracker#reactive-data).

**Comment by janat08** [comment]
Ty for response, error is unclear though

**Comment by Akryum** [comment]
Well, it's trying to use `data` as a property and expect it to have `update({params})`.

**Comment by janat08** [comment]
maybe warn for usage of data?

**Comment by janat08** [comment]
Now it doesn't like this within meteor.
listings() {
      return AuctionItems.find().fetch()
    },

**Comment by janat08** [comment]
@Akryum

**Comment by Herteby** [comment]
I'm pretty sure there's nothing wrong with that piece of code anyway, so your problem must lie elsewhere. You should look through the stack trace, and include it in your question as well.

**Comment by janat08** [comment]
Don't know seems so straightforward that I don't want to explore it.

**Comment by janat08** [comment]
I guess I have to install the new tracker and stuff now even though I'm using components as far as I'm aware.

**Comment by mitar** [comment]
This issue is completely unclear what you are asking. There is no reproduction you prepared. You are asking multiple things in the same issue. You are asking things in already closed issue.

**Comment by janat08** [comment]
Can't help think it's a simple matter of library complaining about format of tracker instruction, which happens in both "separate issues" were I'm basically asking for support, even though components lib doesn't document new tracker use.
