### ISSUE TITLE
Reactive data / subscriptions (i.e. based on route params)

### ISSUE THREAD

**Issue by cpury** [Akryum/vue-meteor-tracker#2]
I'm trying to get a reactive list of data based on a route param. I have this:

```es6
  meteor: {
    subscribe: {
      messages() {
        console.log('subscribe', this.$route.params.term);
        return [ this.$route.params.term ];
      },
    },
    messages() {
      console.log('messages', this.$route.params.term);
      let searchTerm = this.$route.params.term;
      let query = { title: searchTerm };
      return Messages.find(query);
    },
  },
```

This works fine on initial load. However, when navigating (and thus changing the `term` route param), the messages vanish. By looking at the log, I can see that only the subscription was reactively updated, not the data itself (the `messages` function did not run again).

How come? What do I need to do make the data reactive?

**Comment by cpury** [comment]
Hmm, it turns out this is not exactly what happens. Actually, it works fine, as long as the query returns objects. Once I open one that does not return any objects, the `messages` function is not called anymore and I need to navigate away.

Imagine for `term=a` and `term=b` the DB has entries, but not for `term=c`.
Example log output:

```
// I navigate to term=a
subscribe a
messages a
// I navigate to term=b
subscribe b
messages b
// I navigate to term=c
subscribe c
messages c
// I navigate back to term=b
subscribe b
// :(
```

Might this be a bug, that a data function stops being reactive when it was empty once?

**Comment by cpury** [comment]
Hm ok I managed to get it to work by using the advanced `data` notation:

```es6
data: {
      messages: {
        params () {
          return {
            searchTerm: this.$route.params.term
          };
        },
        update ({searchTerm}) {
          let query = { title: searchTerm };
          return Messages.find(query);
        },
      },
    },
```

I'll leave this open nonetheless, since the behavior described above seems rather random.

**Comment by Akryum** [comment]
The correct way to use Vue reactive variables is:

```javascript
messages: {
  params () {
    return this.$route.params.term;
  },
  update (searchTerm) {
    let query = { title: searchTerm };
    return Messages.find(query);
  },
},
```

**Comment by Akryum** [comment]
See the [documentation](https://github.com/Akryum/vue-meteor-tracker#reactive-data)
