### ISSUE TITLE
currentUser global Blaze helper as global Vue mixin

### ISSUE THREAD

**Issue by gustogummi** [Akryum/vue-meteor-tracker#5]
> For code that runs on the client, the global `Meteor.userId()` reactive function will give you the ID of the currently logged in user.
> 
> In addition to that core API, there are some helpful shorthand helpers: `Meteor.user()`, which is exactly equal to calling `Meteor.users.findOne(Meteor.userId())`, and the `{{currentUser}}` Blaze helper that returns the value of `Meteor.user()`.

The `{{currentUser}}` is of course unavailable in Vue and `Meteor.user()` is available only inside of `meteor` option. 

I'm wondering if this package shouldn't come by default with a simple global mixin that reactively provides both `this.currentUser` with `{{currentUser}}` and `this.userId` or `this.currentUserId`.

**Comment by mitar** [comment]
I would be against doing this by default, but providing useful mixin(s) is a good idea.

**Comment by gustogummi** [comment]
The following mixin, imported and injected to the component, will show proper data for test1 but no data for test2. Is it possible to use meteor option in the mixins? Am I missing something?
```
export default {
  computed: {
    test1() {
      return 'test1'
    }
  },
  meteor: {
    test2() {
      return 'test2'
    }
  }
}
```
